[package]
name = "zk-learning"
version = "0.1.0"
authors = ["John Doe <smthwnsn14@mail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.7.1"
zookeeper = "0.5.9"
lazy_static = "1.4.0"
structopt = "0.3.17"